---
- name: Start Container GitLab
  docker_container:
    name: gitlab
    image: "gitlab/gitlab-ce:latest"
    network_mode: host
    state: started
    restart_policy: "always"
    ports:
      - "80:80"
      - "443:443"
 
    volumes:
      - "/srv/gitlab/config:/etc/gitlab"
      - "/srv/gitlab/logs:/var/log/gitlab"
      - "/srv/gitlab/data:/var/opt/gitlab"

- name: Copy configuration gitlab.rb to dir config
  become: true
  templates:
    src: ./templates/gitlab-rb.j2
    dest: /srv/gitlab/config/gitlab.rb

